name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python with caching
      uses: ./
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: requirements.txt
        pip-version: '25.0.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint --disable=C0114,C0115,C0116 $(git ls-files '*.py')
